In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Training.csv")

In [4]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [5]:
df.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,...,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000
mean,0.137805,0.159756,0.021951,0.045122,0.021951,0.162195,0.139024,0.045122,0.045122,0.021951,...,0.021951,0.021951,0.021951,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171
std,0.344730,0.366417,0.146539,0.207593,0.146539,0.368667,0.346007,0.207593,0.207593,0.146539,...,0.146539,0.146539,0.146539,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
df.shape

(4920, 133)

In [7]:
len(df['prognosis'].unique())

41

In [8]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

TRAIN and SPLIT data

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [11]:
X=df.drop("prognosis", axis=1)

In [12]:
y=df['prognosis']

In [22]:
le=LabelEncoder()
le.fit(y)
Y= le.transform(y)

In [14]:
X

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [23]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [24]:
X_train,X_test, y_train,y_test =train_test_split(X,Y, test_size=0.3, random_state=20)

In [25]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

TRAINING TOP MODELS

In [27]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score , confusion_matrix
import numpy as np 

#create an Dictionary to store Models
models ={
    "SVC": SVC(kernel= 'linear'),
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, random_state=42),
    "KNeighbors": KNeighborsClassifier(n_neighbors=5),
    "MultiNomialNB": MultinomialNB()
}

for model_name, model in models.items():
    print(model_name, ":" , model)
    model.fit(X_train, y_train)
    
    #test model
    predictions = model.predict(X_test)
    
    #calculate Accuracy
    accuracy= accuracy_score(y_test, predictions)
    
    #calculate confusion matrix
    
    cm= confusion_matrix(y_test, predictions)
    print(f"{model_name} accuracy : {accuracy}" )
    print(f"{model_name} Confusion matric:")
    print(np.array2string(cm, separator=' , '))

SVC : SVC(kernel='linear')
SVC accuracy : 1.0
SVC Confusion matric:
[[40 ,  0 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 , 43 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 ,  0 , 28 , ... ,  0 ,  0 ,  0] ,
 ... ,
 [ 0 ,  0 ,  0 , ... , 34 ,  0 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 , 41 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 ,  0 , 31]]
RandomForest : RandomForestClassifier(random_state=42)
RandomForest accuracy : 1.0
RandomForest Confusion matric:
[[40 ,  0 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 , 43 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 ,  0 , 28 , ... ,  0 ,  0 ,  0] ,
 ... ,
 [ 0 ,  0 ,  0 , ... , 34 ,  0 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 , 41 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 ,  0 , 31]]
Gradient Boosting : GradientBoostingClassifier(random_state=42)
Gradient Boosting accuracy : 1.0
Gradient Boosting Confusion matric:
[[40 ,  0 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 , 43 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 ,  0 , 28 , ... ,  0 ,  0 ,  0] ,
 ... ,
 [ 0 ,  0 ,  0 , ... , 34 ,  0 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 , 41 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 ,  0 , 31]]
KNeighbors : KNeighborsClassifier()
KNeighbors accuracy : 1.0
KNeighbors Confusion matric:
[[40 ,  0 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 , 43 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 ,  0 , 28 , ... ,  0 ,  0 ,  0] ,
 ... ,
 [ 0 ,  0 ,  0 , ... , 34 ,  0 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 , 41 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 ,  0 , 31]]
MultiNomialNB : MultinomialNB()
MultiNomialNB accuracy : 1.0
MultiNomialNB Confusion matric:
[[40 ,  0 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 , 43 ,  0 , ... ,  0 ,  0 ,  0] ,
 [ 0 ,  0 , 28 , ... ,  0 ,  0 ,  0] ,
 ... ,
 [ 0 ,  0 ,  0 , ... , 34 ,  0 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 , 41 ,  0] ,
 [ 0 ,  0 ,  0 , ... ,  0 ,  0 , 31]]

In [28]:
#Model Creation
svc =SVC(kernel='linear')
svc.fit(X_train,y_train)
ypred = svc.predict(X_test)
accuracy_score(y_test,ypred)

1.0

In [30]:
#saving the model
import pickle
pickle.dump(svc,open("svc.pkl", 'wb'))

In [32]:
#load Model
svc = pickle.load(open("svc.pkl", 'rb'))
svc

SVC(kernel='linear')

In [33]:
X_test

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
4037,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4191,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
432,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1266,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3765,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2327,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1906,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
X_test.iloc[0].values

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

LOAD DATABASE and usig Logic for recommendations

In [46]:
sys_des = pd.read_csv("symtoms_df.csv")
precaustions = pd.read_csv("precautions_df.csv")
work_out = pd.read_csv("workout_df.csv")
description = pd.read_csv("description.csv")
medication = pd.read_csv("medications.csv")
diets = pd.read_csv("diets.csv")

In [47]:
diets

,Disease,Diet
0,Fungal infection,"['Antifungal Diet', 'Probiotics', 'Garlic', 'C..."
1,Allergy,"['Elimination Diet', 'Omega-3-rich foods', 'Vi..."
2,GERD,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
3,Chronic cholestasis,"['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot..."
4,Drug Reaction,"['Antihistamine Diet', 'Omega-3-rich foods', '..."
5,Peptic ulcer disease,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
6,AIDS,"['Balanced Diet', 'Protein-rich foods', 'Fruit..."
7,Diabetes,"['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea..."
8,Gastroenteritis,"['Bland Diet', 'Bananas', 'Rice', 'Applesauce'..."
9,Bronchial Asthma,"['Anti-Inflammatory Diet', 'Omega-3-rich foods..."
10,Hypertension,"['DASH Diet', 'Low-sodium foods', 'Fruits and ..."
11,Migraine,"['Migraine Diet', 'Low-Tyramine Diet', 'Caffei..."
12,Cervical spondylosis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
13,Paralysis (brain hemorrhage),"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
14,Jaundice,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
15,Malaria,"['Malaria Diet', 'Hydration', 'High-Calorie Di..."
16,Chicken pox,"['Chicken Pox Diet', 'High-Calorie Diet', 'Sof..."
17,Dengue,"['Dengue Diet', 'Hydration', 'High-Calorie Die..."
18,Typhoid,"['Typhoid Diet', 'High-Calorie Diet', 'Soft an..."
19,hepatitis A,"['Hepatitis A Diet', 'High-Calorie Diet', 'Sof..."
20,Hepatitis B,"['Hepatitis B Diet', 'High-Calorie Diet', 'Sof..."
21,Hepatitis C,"['Hepatitis C Diet', 'High-Calorie Diet', 'Sof..."
22,Hepatitis D,"['Hepatitis D Diet', 'High-Calorie Diet', 'Sof..."
23,Hepatitis E,"['Hepatitis E Diet', 'High-Calorie Diet', 'Sof..."
24,Alcoholic hepatitis,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
25,Tuberculosis,"['TB Diet', 'High-Calorie Diet', 'Soft and bla..."
26,Common Cold,"['Cold Diet', 'Hydration', 'Warm fluids', 'Res..."
27,Pneumonia,"['Pneumonia Diet', 'High-Calorie Diet', 'Soft ..."
28,Dimorphic hemmorhoids(piles),"['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra..."
29,Heart attack,"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
30,Varicose veins,"['Varicose Veins Diet', 'High-Fiber Diet', 'Fr..."
31,Hypothyroidism,"['Hypothyroidism Diet', 'Iodine-rich foods', '..."
32,Hyperthyroidism,"['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C..."
33,Hypoglycemia,"['Hypoglycemia Diet', 'Complex carbohydrates',..."
34,Osteoarthristis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
35,Arthritis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
36,(vertigo) Paroymsal Positional Vertigo,"['Vertigo Diet', 'Low-Salt Diet', 'Hydration',..."
37,Acne,"['Acne Diet', 'Low-Glycemic Diet', 'Hydration'..."
38,Urinary tract infection,"['UTI Diet', 'Hydration', 'Cranberry juice', '..."
39,Psoriasis,"['Psoriasis Diet', 'Anti-Inflammatory Diet', '..."
40,Impetigo,"['Impetigo Diet', 'Antibiotic treatment', 'Fru..."

In [ ]:
#Model Predicition Function

def get_predicted_value(patient_symptoms)